# This is a basic workflow to help you get started with Actions

name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*-*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/devops_coe_robot:$RELEASE_VERSION
    - name: Docker Login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_TOKEN}}
    - name: Push Image
      run: docker push ${{secrets.DOCKER_USER}}/devops_coe_robot:$RELEASE_VERSION
    
